security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users:
            entity: { class: 'App\Entity\User' }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: users
            lazy: true
            custom_authenticators:
                - App\Security\WaxAuthenticator
            logout:
                path: user_logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
